# Import Modules

In [1]:
import pandas as pd
import pycaret.classification as pyc

# Load Data

In [2]:
df = pd.read_csv('heart.csv')

In [3]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

# Train and Evaluate Model

In [5]:
cat_features = ['Sex', 'ChestPainType', 'FastingBS', 'RestingECG', 'ExerciseAngina', 'ST_Slope']

In [6]:
clf = pyc.setup(df, target='HeartDisease',
             categorical_features=cat_features,
             train_size=0.9)

In [7]:
best_model = pyc.compare_models()

Processing:   0%|          | 0/69 [00:00<?, ?it/s]

# Test Model

In [8]:
pyc.predict_model(best_model, df.tail())

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,prediction_label,prediction_score
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1,1,0.68
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1,1,0.98
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1,1,0.98
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1,1,0.72
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0,0,0.99